#!/bin/bash

echo "Setting up local environment variables..."
echo "Please add the following environment variables to your .env.local file:"
echo ""
echo "NOTION_TOKEN=YOUR_NOTION_TOKEN_HERE"
echo "NOTION_DATABASE_ID=YOUR_NOTION_DATABASE_ID_HERE"
echo "SENDGRID_API_KEY=YOUR_SENDGRID_API_KEY_HERE"
echo "SENDGRID_FROM_EMAIL=thearc@thearcme.com"
echo "OPENAI_API_KEY=YOUR_OPENAI_API_KEY_HERE"
echo ""
echo "To get your SendGrid API key:"
echo "1. Go to https://app.sendgrid.com/settings/api_keys"
echo "2. Create a new API key with 'Mail Send' permissions"
echo "3. Copy the key and replace YOUR_SENDGRID_API_KEY_HERE"
echo ""
echo "To get your OpenAI API key:"
echo "1. Go to https://platform.openai.com/api-keys"
echo "2. Create a new API key"
echo "3. Copy the key and replace YOUR_OPENAI_API_KEY_HERE"
echo ""
echo "After updating .env.local, restart your development server."
